#!/bin/bash

REDUNDANCY='1'
BANDWIDTH='10Mbps'
DELAY='50ms'
BUFFER='3'
N_LEAF='1'
for BLOCK_SIZE in '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15' '16' '17' '18' '19' '20'
do
    for ERROR_P in '0.00' '0.01' '0.03' '0.05'
    do
        timedatectl | grep Local >> output.txt

        ./waf --run "scratch/tcp-bbr-exam --nLeaf=$N_LEAF --bandwidth=$BANDWIDTH --delay=$DELAY --qSize=$BUFFER --redundancy=$REDUNDANCY --fec_block_size=$BLOCK_SIZE --error_p=$ERROR_P" >> output.txt

        echo " " >> output.txt
    done
done